### ISSUE TITLE
Propuesta agregar inyección dependencias

### ISSUE THREAD

**Issue by luispe** [nemesiscodex/actix-blog-app#2]
¡Buenas!, antes que nada perdón por la ignorancia.
Pero quería dejar una propuesta para saber su opinión acerca de que posibilidades hay de agregar algunas capas mas de asbtracción y en mi opinióin ganar mayor tolerancia al cambio.

A continuación le dejo la propuesta para saber su opinión

Development flow

client-req ---> handlers.rs (serialize and deserialize) ---> usecase.rs (business validation) ---> repository (orchestation) ---> obtain data (persistence or external service)

```sh
actix-blog-app/
|── src
    |── infrastructure
        |── rest (?)
            handlers.rs -> (only comunicate with usecase layer (business logic))
            serialize and deserialize external client request.
        |── persistence
            psql.rs -> (adapter implements respository interface or trait (?))
    |── models
        model.rs (contain only struct with data model system)
    |── repository
        repository.rs (orchestration to get the data from one or more places, ex: postgres, redis, external service, etc... In this layer inject differents infrastructure impl)
    |── usecase
        usecase.rs (business logic and comunicate with repository layer for obtain data to return handler req)
    
    config.rs
    ...etc
    main.rs
```

Muchas gracias de ante mano

**Comment by nemesiscodex** [comment]
Es el clean architecture, no? Es interesante, encontre esto que podria darnos algunas ideas de como implementarlo https://11takanori.medium.com/dependency-inversion-in-rust-web-application-479d54d5242e

**Comment by luispe** [comment]
Así es @nemesiscodex, arquitectura hexagonal.
Excelente el post 🙂.
Voy a ver si puedo agregar algunas capas entre el handler y la obtención de datos y si logro llegar a algo bueno te aviso.

**Comment by nemesiscodex** [comment]
Muchas gracias @LuisPe !
